name: NASA Project CI
on: #on push to master / pr to master
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: #reusable actions / scripts
      - uses: actions/checkout@v2
      - name: Use Node.js version 16 #optionally we can give name to the task
        uses: actions/setup-node@v2
        with: #options for above action
          node-version: '16'
      - run: npm install #run our own commands
      - run: npm run build --prefix client
